<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- NuGet Paket Bilgileri -->
    <IsPackable>true</IsPackable>
    <PackageId>Simplex.Localization.Middleware</PackageId>
    <Version>1.0.1</Version>
    <Authors>SimplexBT</Authors>
    <Description>ASP.NET Core Boru Hattı için Otomatik JSON Yanıt Yerelleştirme (Localization) Middleware Paketi</Description>
    <PackageTags>localization;middleware;aspnetcore;json;translate</PackageTags>
    <RepositoryUrl>https://github.com/Enes0668/localization</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Enes0668/localization</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <Content Update="Localization\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

</Project>
